spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/showcase
    driver-class-name: org.postgresql.Driver
    username: crafted
    password: code

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect