debug: false

logging:
  level:
    root: INFO
    org.hibernate: WARN

server:
  port: 8098
  error:
    include-message: always
    include-stacktrace: never

spring:
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: development, h2-test
  cache:
    type: simple
  application:
    name: Essencium Application
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        globally_quoted_identifiers: true
  freemarker:
    enabled: false
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    dispatch-trace-request: true

mail:
  host: localhost
  port: 587
  username: devnull@frachtwerk.de
  password: changeme

  default-sender:
    name: Essencium Mailer
    address: devnull@frachtwerk.de

  smtp:
    auth: true
    start-tls: true

  branding:
    logo: https://static.frachtwerk.de/frachtwerk_320px.png
    name: ${spring.application.name}
    url: ${app.url}
    primary-color: "#00b5d6"
    text-color: "#ffffff"

  new-user-mail:
    subject-key: mail.new-user.subject
    template: NewUserMessage.ftl
    reset-link: setPassword?token=

  reset-token-mail:
    subject-key: mail.reset-token.subject
    template: ResetTokenMessage.ftl
    reset-link: setPassword?token=

  contact-mail:
    subject-prefix-key: mail.contact.subject.prefix
    recipients:
      - devnull@frachtwerk.de
    template: ContactMessage.ftl
    locale: de

  new-login-mail:
    subject-key: mail.new-login.subject
    template: NewLoginMessage.ftl

app:
  domain: localhost
  url: http://${app.domain}:8098
  auth:
    jwt:
      access-token-expiration: 86400 # 24 hours
      refresh-token-expiration: 2592000 # 30 days
      issuer: Frachtwerk GmbH
      cleanup-interval: 3600 # 1 hour
      max-session-expiration-time: 86400 # 24 hours
  cors:
    allow: false
  security:
    min-password-strength: 1
    max-failed-logins: 10

swagger:
  base-url: ${app.url}

management:
  health:
    ldap:
      enabled: false
  endpoints:
    web:
      exposure:
        include: info, health

pom:
  version: '@project.version@'

essencium:
  init:
    roles:
      - name: ADMIN
        description: Administrator
        rights: []
        protected: true
        default-role: true
    users:
      - first-name: Admin
        last-name: User
        username: devnull@frachtwerk.de
        password: adminAdminAdmin
        roles:
          - ADMIN
  jpa:
    table-prefix: "FW_"
    camel-case-to-underscore: true